ReservaEscenario/ReservaEscenario/urls.py
from django.conf.urls import  include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('reserva.urls', namespace="reserva")),
    # url('', include('social_django.urls', namespace='social'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ReservaEscenario/reserva/urls.py
from django.conf.urls import url
from .import views

urlpatterns=[
    url(r'^',views.login,name='login'),
    url(r'^administrar/$',views.administrar,name='administrar'),
    url(r'^escenarios/lista/$',views.listarEscenario,name='listarEscenario'),
    url(r'^escenarios/agregar/$',views.agregarEscenario,name='agregarEscenario'),
    url(r'^escenarios/(?P<idescenario>\d+)//$',views.actualizarEscenario,name='actualizarEscenario'),
    url(r'^escenarios/(?P<idescenario>\d+)/eliminar/$',views.eliminarEscenario,name='eliminarEscenario'),
    url(r'^presentaciones/lista/$',views.listarPresentacion,name='listarPresentacion'),
    url(r'^presentaciones/agregar/$',views.agregarPresentacion,name='agregarPresentacion'),
    url(r'^presentaciones/(?P<idimg>\d+)/$',views.actualizarPresentacion,name='actualizarPresentacion'),
    url(r'^presentaciones/(?P<idimg>\d+)/eliminar/$',views.eliminarPresentacion,name='eliminarPresentacion'),
    url(r'^agregarPresentacion/$',views.agregarPresentacion,name='agregarPresentacion'),
    url(r'^reservarEvento/$',views.reservarEvento,name='reservarEvento'),
    url(r'^confirmarEvento/$',views.confirmarEvento,name='confirmarEvento'),
    url(r'^requerimientos/$',views.requerimientos,name='requerimientos'),
    url(r'^prinEventos/$', views.prinEventos, name='prinEventos'),
    url(r'^observacionesEvento/$', views.observacionesEvento, name='observacionesEvento'),
]

ReservaEscenario/reserva/forms.py
from django import  forms
from django.forms import  ModelForm
from .models import Evento
from .models import  Comentario
from .models import ImgEscenario
from .models import Escenario
from django.utils.translation import ugettext_lazy as _


class loginForm(forms.Form):
    username=forms.CharField(max_length=50,
                             widget= forms.TextInput(attrs={
                                 'type':'email'
                             }))
    password=forms.CharField(max_length=50,widget=forms.TextInput(attrs={
                                 'type':'password'

                            }))
class datosEscenario(forms.ModelForm):
    class Meta:
        model = Escenario
        fields = ['nombre_escenario','tipo_escenario','ubicacion','estado']
        labels = {
            'nombre_escenario':_('Nombre del escenario'),
            'tipo_escenario':_('Tipo de escenario'),
            'ubicacion':_('Ubicacion del escenario'),
            'estado':_('Estado del escenario'),

        }
        widgets = {
            'nombre_escenario': forms.TextInput(attrs ={'id':'nombre_escenario','class': 'form-group row form-control '}),
            'tipo_escenario': forms.Select(attrs={'id':'tipo_escenario','class': 'form-group row form-control '}),
            'ubicacion': forms.TextInput(attrs={'id':'ubicacion','class': 'form-group row form-control '}),
            'imagen': forms.FileInput(attrs={'id':'imagen','class': 'form-group row form-control '}),
            'estado': forms.Select(attrs={'class': 'form-group row form-control '}),
        }

class datosEvento(forms.ModelForm):
    class Meta:
        model= Evento
        fields=['nombre_evento','capacidad_evento','tipo_evento', 'objetivo','fecha','hora','medio_difusion', 'req_internet','escenario']
        labels = {

            'nombre_evento': _('Nombre del evento:'),
            'escenario':_('Escenario elegido:'),
            'capacidad_evento': _('Capacidad del evento:'),
            'tipo_evento':_('Tipo de Evento:'),
            'objetivo': _('Objetivo del Evento:'),
            'fecha': _('Fecha programada para el evento:'),
            'hora': _('Hora del evento:'),
            'medio_difusion': _('¿Como desea difundir su evento?'),
            'req_internet': _('¿Requiere Internet?'),


        }
        widgets = {

            'nombre_evento': forms.TextInput(attrs={'id':'nombre_evento','class': 'form-group row form-control '}),
            'escenario': forms.Select(attrs={'id':'escenario','class': 'form-group row form-control '}),
            'capacidad_evento': forms.TextInput(attrs={'id':'capacidad_evento','class': 'form-group row form-control'}),
            'tipo_evento': forms.Select(attrs={'id':'tipo_evento' ,'class': 'form-group row form-control','selected':'selected'}),
            'objetivo': forms.Textarea(attrs={'id':'objetivo','class': 'form-group row form-control'}),
            'fecha':forms.DateInput(attrs={'id':'fecha','class': 'form-group row form-control '  }),
            'hora': forms.DateTimeInput(attrs={'id':'hora','class': 'form-group row form-control'}),
            'medio_difusion': forms.FileInput(attrs={'id':'medio_difusion','class': 'form-control-file'}),
            'req_internet': forms.CheckboxInput(attrs={'id':'req_internet','class': ' form-check form-check-input ','type':"checkbox" }),
            'escenario': forms.Select(attrs={'class': 'form-group row form-control '}),

        }

            #VALIDACIONES

        #Validacion de campo nombre_evento

        def clean_nombre_evento(self):
            diccionario_limpio = self.cleaned_data
            nombre_evento = diccionario_limpio.get('nombre_evento')
            if len(nombre_evento) > 200:
                raise forms.ValidationError("El nombre del evento debe ser menor a 200 caracteres")

            return nombre_evento

        def clean_nombre_evento(self):
            diccionario_limpio = self.cleaned_data
            nombre_evento = diccionario_limpio.get('nombre_evento')
            if len(nombre_evento) < 1:
                raise forms.ValidationError("El nombre del evento es obligatorio")

            return nombre_evento
        #Validacion de campo capacidad_evento

        def clean_capacidad_evento(self):
            diccionario_limpio = self.cleaned_data
            capacidad_evento = diccionario_limpio.get('capacidad_evento')
            if len(capacidad_evento) < 1:
                raise  forms.ValidationError("El campo capacidad del evento es obligatorio")

            return capacidad_evento

        def clean_capacidad_evento(self):
            diccionario_limpio = self.cleaned_data
            capacidad_evento = diccionario_limpio.get('capacidad_evento')
            if not capacidad_evento.isalnum():
                raise  forms.ValidationError("El campo solo admite numeros")

            return capacidad_evento


class presEscenario(forms.ModelForm):
    class Meta:
        model=ImgEscenario
        fields =['presentacion','escenario']
        labels ={

            'presentacion': _('¿Como desea acomodar el escenario?'),
            'escenario':_('Nombre de Escenario')

        }
        widgets = {
            'presentacion' : forms.FileInput(attrs={'class': 'form-group row '}),
            'escenario': forms.Select(attrs={'class': 'form-group row form-control ' }),

        }




class datosComentario(forms.ModelForm):
    class Meta:
        model= Comentario
        fields =['contenido']
        labels={


            'contenido': _('Observaciones del evento:')
                }

ReservaEscenario/reserva/views.py
from django.shortcuts import render_to_response,get_object_or_404, render,HttpResponseRedirect
from django.urls import reverse
from django.views.generic import TemplateView, FormView, CreateView, DetailView, UpdateView, DeleteView
from .forms import loginForm
from django.shortcuts import redirect
from .models import Escenario
from .models import Evento
from .forms import datosEvento
from .forms import datosComentario
from .forms import datosEscenario
from .models import  ImgEscenario
from .forms import presEscenario
from django.contrib import  messages
from django.core.urlresolvers import reverse, reverse_lazy

from .forms import presEscenario
# Create your views here.

def login(request):
    lista_escenarios = Escenario.objects.all()
    return render_to_response(
        'login.html',
        {'lista_escenarios': lista_escenarios,

         })
def listarEscenario(request):
    return render_to_response("escenarios.html", {"lista_escenarios": Escenario.objects.all(), "messages": messages.get_messages(request)})




def agregarEscenario(request):

    if request.method == 'POST':
        form = datosEscenario(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "El escenario ha sido guardado!")
            return redirect(reverse('reserva:listarEscenario'))

    else:
        form=datosEscenario()
    return render(request, 'altaEscenario.html', {'form': form})

def actualizarEscenario(request, idescenario):
    instance= get_object_or_404(Escenario, id=idescenario)
    form=datosEscenario(request.POST ,request.FILES, instance=instance)
    if request.method=='POST':
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "El escenario ha sido actualizado!")
            return redirect(reverse('reserva:listarEscenario'))
    else:
        form=datosEscenario(instance=instance)
    return render(request, 'altaEscenario.html',{
                                    'form':form,'instance':instance
                                    })
def eliminarEscenario(request,idescenario):
    instance=get_object_or_404(Escenario, id=idescenario)
    instance.delete()
    messages.add_message(request, messages.SUCCESS, "El escenario ha sido eliminado con exito" )
    return redirect(reverse('reserva:listarEscenario'))

def listarPresentacion(request):
    return render_to_response("presentaciones.html", {"lista_presentaciones": ImgEscenario.objects.all(), "messages": messages.get_messages(request)})

def agregarPresentacion(request):

    if request.method == 'POST':
        form = presEscenario(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "La presentacion ha sido guardada!")
            return redirect(reverse('reserva:listarPresentacion'))

    else:
        form=presEscenario()
    return render(request, 'altaPresentacion.html', {'form': form})

def actualizarPresentacion(request, idimg):
    instance= get_object_or_404(ImgEscenario, id=idimg)
    form=presEscenario(request.POST ,request.FILES, instance=instance)
    if request.method=='POST':
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "La presentacion ha sido actualizada!")
            return redirect(reverse('reserva:listarPresentacion'))
    else:
        form=datosEscenario(instance=instance)
    return render(request, 'altaPresentacion.html',{
                                    'form':form,'instance':instance
                                    })
def eliminarPresentacion(request,idimg):
    instance=get_object_or_404(ImgEscenario, id=idimg)
    instance.delete()
    messages.add_message(request, messages.SUCCESS, "La presentacion ha sido eliminado con exito" )
    return redirect(reverse('reserva:listarPresentacion'))



def prinEventos(request):

    lista_escenarios=Escenario.objects.all()
    return render_to_response(
        'index.html',
        {'lista_escenarios': lista_escenarios,

         })


def reservarEvento(request):
    lista_escenarios = Escenario.objects.all()
    if request.method == 'POST':  # Si el usuario esta enviando el formulario con datos
        nombre_evento = request.POST['nombre_evento']
        capacidad_evento = request.POST['capacidad_evento']
        tipo_evento = request.POST['tipo_evento']
        objetivo = request.POST['objetivo']
        fecha = request.POST['fecha']
        hora = request.POST['hora']
        medio_difusion = request.POST['medio_difusion']
        req_internet = request.POST['req_internet']

        presentacion = request.POS['presentacion']
        escenario = request.POST['escenario']

        form = datosEvento(
            {'nombre_evento': nombre_evento, 'capacidad_evento': capacidad_evento, 'tipo_evento': tipo_evento,
             'objetivo': objetivo, 'fecha': fecha, 'hora': hora, 'medio_difusion': medio_difusion,
             'req_internet': req_internet})
        formPresentaciones = presEscenario({'presentacion': presentacion, 'escenario': escenario})


        if form.is_valid():
            #evento = form.cleaned_data['nombre_evento']
            form.save()  # Guardar los datos en la base de datos
            formPresentaciones.save()
            #return render(request, 'home.html', { 'evento', evento })
    else:
        form = datosEvento()
        formPresentaciones = presEscenario()#
    return render_to_response('eventoProgramado.html',
                                  {'form': form,
                                   'lista_escenarios': lista_escenarios,})



def confirmarEvento(request):
    car_evento = Evento.objects.all()
    if request.method == 'POST':  # Si el usuario esta enviando el formulario con datos
        nombre_evento= request.POST['nombre_evento']
        capacidad_evento =request.POST['capacidad_evento']
        tipo_evento=request.POST['tipo_evento']
        objetivo=request.POST['objetivo']
        fecha=request.POST['fecha']
        hora=request.POST['hora']
        medio_difusion=request.POST['medio_difusion']
        req_internet=request.POST['req_internet']

        presentacion=request.POS['presentacion']
        escenario=request.POST['escenario']

        form = datosEvento({'nombre_evento':nombre_evento,'capacidad_evento':capacidad_evento,'tipo_evento':tipo_evento,
                            'objetivo':objetivo,'fecha':fecha,'hora':hora,'medio_difusion':medio_difusion,'req_internet':req_internet})
        formPresentaciones = presEscenario({'presentacion':presentacion,'escenario':escenario})
         # Formulario lleno, pero con datos NO validos
        if form.is_valid() and formPresentaciones.is_valid() :
            #evento = form.cleaned_data['nombre_evento']
            form.save()
            formPresentaciones.save()# Guardar los datos en la base de datos
            #return render(request, 'home.html', { 'evento', evento })
    else:
        form = datosEvento()
        formPresentaciones = presEscenario()#



    return render_to_response('eventoNProgramado.html',
                                  {'form': form,
                                   'car_evento': car_evento,})



def observacionesEvento(request):
    if request.method == 'POST':
        form =datosComentario(request.POST)
        if form.is_valid():
            form.save()
    else:
        form=datosComentario()
        return render_to_response('retroEvento.html',{
                                    'form':form})




def administrar(request):

    lista_escenarios=Escenario.objects.all()
    return render_to_response(
        'admin.html',
        {'lista_escenarios': lista_escenarios,

         })
def requerimientos(request):

    car_evento=Evento.objects.all()
    return render_to_response(
        'areas.html',
        {'car_evento':car_evento,
        }

    )

ReservaEscenario/reserva/templates/admin.html
{% extends 'base.html' %}

{% load static from staticfiles %}
{% block styles %}

        <link rel="stylesheet" href="{%  static 'reserva/css/admin.css' %}">
        <script href="{% static 'reserva/jquery/jquery.min.js' %}"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
        <link rel="stylesheet" href="static/reserva/css/font-awesome-4.7.0/css/font-awesome.min.css">
{% endblock styles %}

{% block title %}|Administrar{% endblock %}

{% block content %}

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Start Bootstrap
                    </a>
                </li>
                <li>
                    <a href="#">Dashboard</a>
                </li>
                <li>
                    <a href="{% url 'reserva:listarEscenario' %}">Ver todos los escenarios</a>
                </li>
                <li>
                    <a href="{% url 'reserva:agregarEscenario' %}">Agregar Escenario</a>
                </li>
                <li>
                    <a href="{% url 'reserva:agregarPresentacion' %}">Agregar Presentacion </a>
                </li>
                 <li>
                    <a href="{% url 'reserva:listarPresentacion' %}">Ver Presentaciones </a>
                </li>

                <li>
                    <a href="#">Ver todos los eventos</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <a href="#menu-toggle" class="btn btn-default hidden-md-up" id="menu-toggle"> <i class="fa fa-outdent fa-2x"></i> Menu </a>
            <div class="container">
                <div class="row">
                    <div class="col col-lg-12 col-md-3">
                        <div class="row">

                        <div class="col" >
                                <!-- Indicates a successful or positive action -->

                                <button type="button" class=" btnEventos rounded btn btn-success"><i class="fa fa-check-square"> </i>  Atendidos</button>
                        </div>

                        <div class="col">
                            <!-- Contextual button for informational alert messages -->
                                <button type="button" class="btnEventos btn btn-info"><i class="fa fa-thumbs-o-up"></i> Confirmados </button>
                        </div>

                        <div class="col">
                            <!-- Indicates caution should be taken with this action -->
                                <button type="button" class="btnEventos btn btn-warning"><i class="fa fa-exclamation-triangle"></i> Pendientes</button>

                        </div>
                        <div class="col">
                                    <!-- Indicates a dangerous or potentially negative action -->
                                <button type="button" class="btnEventos btn btn-danger"><i class="fa fa-window-close"></i> Cancelados</button>
                        </div>
                            </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->





{% endblock content %}

{% block scripts %}

     <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
 {% endblock scripts %}

ReservaEscenario/reserva/templates/altaPresentacion.html
{% extends 'base.html' %}

{% load static from staticfiles %}
{% block styles %}
<meta charset="UTF-8">
<link rel="stylesheet" href="{%  static 'reserva/css/altaEscenario.css'%}">
<script href="{% static 'reserva/jquery/jquery.min.js' %}"></script>
<link rel="stylesheet" href="static/reserva/css/font-awesome-4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
{% endblock styles %}



{% block title %}|agregarPresentacion{% endblock %}

{% block content %}

<div class="container" id="formEscenario">
    <div class="row">

        <div class="col-sm-12 ">


            <h4 class="lead">Agregar Presentacion de Escenario</h4>
            <hr class="my-4">
            <form role="form" method="POST" action="" enctype="multipart/form-data" >{% csrf_token %}

                {{ form.presentacion.label_tag}} {{form.presentacion.as_widget}}<span id="al1"></span><br>

                {{ form.escenario.label_tag}} {{ form.escenario.as_widget }}<span id="al2"></span><br>



                <button type="submit" class="btn btn-primary btn-lg"> Agregar presentacion a escenario</button>



            </form>

        </div>



    </div>



</div>
{% endblock content %}

ReservaEscenario/reserva/templates/escenarios.html
{% extends 'base.html' %}

{% load static from staticfiles %}
{% block styles %}
<meta charset="UTF-8">
<link rel="stylesheet" href="{%  static 'reserva/css/eventoProgramado.css'%}">
<script href="{% static 'reserva/jquery/jquery.min.js' %}"></script>
<script src="{% static 'reserva/jquery/jquery.datetimepicker.full.js'%}"></script>
<link rel="stylesheet" href="{% static 'reserva/css/jquery.datetimepicker.min.css'%}">
<link rel="stylesheet" href="static/reserva/css/font-awesome-4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
{% endblock styles %}



{% block title %}|Escenarios{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <!-- mostramos los mensajes flash -->
        {% if messages %}
        <div class="alert alert-success">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>
        {% endif %}
        <div class="jumbotron ">

            {% if lista_escenarios|length > 0 %}
            <h4 class="lead">Escenarios</h4>
            <hr class="my-4">
            {% for Escenario in lista_escenarios %}
            <div class="col col-md-12" >
                <div class="container">
                    <div class="row">
                        <div class=" col ">
                            <div class="card w-50" style="width: 20rem;">
                                <img class="card-img-top" src="{{ Escenario.imagen.url }} " alt="Card image ">
                                <div class="card-block">

                                    <h4 class="card-title">{{ Escenario.nombre_escenario}}</h4>



                                </div>
                            </div>
                            <hr class="my-4">
                        </div>


                        <div class="col ">
                            <a href="{% url 'reserva:actualizarEscenario' Escenario.id %}" class="btn btn-success">Actualizar escenario</a>
                            <a href="{% url 'reserva:eliminarEscenario' Escenario.id %}" class="btn btn-danger">Eliminar escenario</a>
                        </div>

                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>No hay escenarios</p>
            {% endif %}

        </div>
    </div>
</div>
{% endblock content %}

ReservaEscenario/reserva/templates/index.html
{% extends 'base.html' %}

{% load static from staticfiles %}
{% block styles %}

        <link rel="stylesheet" href="{%  static 'reserva/css/prinEventos.css'%}">
        <script href="{% static 'reserva/jquery/jquery.min.js' %}"></script>
         <link rel="stylesheet" href="{% static 'reserva/css/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
{% endblock styles %}



{% block title %}|Eventos{% endblock %}

{% block content %}

<div id="wrapper">

    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                <a href="#">
                    Start Bootstrap
                </a>
            </li>
            <li>
                <a href="#">Mis eventos</a>
            </li>
            <li>
                <a href="#">Eventos proximos</a>
            </li>
            <li>
                <a href="#">Overview</a>
            </li>
            <li>
                <a href="#">Events</a>
            </li>

            <li>
                <a href="#">Services</a>
            </li>
            <li>
                <a href="#">Contact</a>
            </li>
        </ul>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        <a href="#menu-toggle" class="btn btn-default hidden-md-up" id="menu-toggle"> <i class="fa fa-outdent fa-2x"></i> Menu </a>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="container">
                        <div class="row">
                            <div class="col-12">



                                <div class="jumbotron">
                                    <h1 class="display-4">Reserva!</h1>
                                    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
                                    <hr class="my-4">
                                    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
                                    <p class="lead">

                                        <a class="btn btn btn-md" href="{% url 'reserva:reservarEvento' %}" role="button">Reservar escenario </a>
                                        <a class="btn btn btn-md" href="{% url 'reserva:confirmarEvento' %}" role="button">Confirmar escenario </a>

                                    </p>
                                </div>
                            </div>


                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

<!-- Menu Toggle Script -->





{% endblock content %}

{% block scripts %}

<script>

    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
</script>
{% endblock scripts %}

ReservaEscenario/reserva/templates/presentaciones.html
{% extends 'base.html' %}

{% load static from staticfiles %}
{% block styles %}
<meta charset="UTF-8">
<link rel="stylesheet" href="{%  static 'reserva/css/eventoProgramado.css'%}">
<script href="{% static 'reserva/jquery/jquery.min.js' %}"></script>
<script src="{% static 'reserva/jquery/jquery.datetimepicker.full.js'%}"></script>
<link rel="stylesheet" href="{% static 'reserva/css/jquery.datetimepicker.min.css'%}">
<link rel="stylesheet" href="static/reserva/css/font-awesome-4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
{% endblock styles %}



{% block title %}|Presentaciones{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <!-- mostramos los mensajes flash -->
        {% if messages %}
        <div class="alert alert-success">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>
        {% endif %}
        <div class="jumbotron ">

            {% if lista_presentaciones|length > 0 %}
            <h4 class="lead">Presentaciones</h4>
            <hr class="my-4">
            {% for ImgEscenario in lista_presentaciones %}
            <div class="col col-md-12" >
                <div class="container">
                    <div class="row">
                        <div class=" col ">
                            <div class="jumbotron">
                                    <h1 class="display-4">{{ ImgEscenario.escenario}}</h1>

                                    <p class="lead">

                                        <img src="{{ ImgEscenario.presentacion.url}}">

                                    </p>
                            </div>

                        </div>


                        <div class="col ">
                            <a href="{% url 'reserva:actualizarPresentacion' ImgEscenario.id %}" class="btn btn-success">Actualizar presentacion</a>
                            <a href="{% url 'reserva:eliminarPresentacion' ImgEscenario.id %}" class="btn btn-danger">Eliminar presentacion</a>
                        </div>

                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>No hay presentaciones disponibles</p>
            {% endif %}

        </div>
    </div>
</div>
{% endblock content %}